export const data = [
  {
    ActivityId: 11973,
    BusinessCourseId: 0,
    CourseName: "会计审计电算化周六1-2",
    Id: 24285,
    StartLesson: 1,
    EndLesson: 2,
    TeacherName: "吴海东,杨隆浩",
    Week: 3,
    WeekDay: "周六",
  },
  {
    ActivityId: 11973,
    Id: 24284,
    CourseName: "电子商务综合实验周六1-2",
    StartLesson: 1,
    EndLesson: 2,
    TeacherName: "吴海东,杨隆浩",
    UserId: 131,
    Week: 3,
    WeekDay: "周六",
  },
  {
    ActivityId: 11972,
    CourseName: "多元统计分析周四1-4",
    ActivityName: "1",
    Id: 24283,
    TeacherName: "吴海东,杨隆浩",
    StartLesson: 1,
    EndLesson: 4,
    Week: 3,
    WeekDay: "周四",
  },
  {
    CourseName: "英语周三5-6",
    Id: 24209,
    StartLesson: 5,
    EndLesson: 6,
    UserId: 1136,
    Week: 3,
    TeacherName: "吴海东,杨隆浩",
    WeekDay: "周三",
  },
  {
    CourseName: "数字营销与商业智能周一7-8",
    Id: 24136,
    StartLesson: 7,
    EndLesson: 8,
    Week: 3,
    TeacherName: "吴海东,杨隆浩",
    WeekDay: "周一",
  },
  {
    CourseName: "数据库原理周三3-4",
    StartLesson: 3,
    EndLesson: 4,
    Week: 3,
    WeekDay: "周三",
    TeacherName: "吴海东,杨隆浩",
  },
  {
    CourseName: "数据库应用周一1-2",
    Id: 24098,
    StartLesson: 1,
    EndLesson: 2,
    UserId: 1136,
    Week: 3,
    WeekDay: "周一",
    TeacherName: "吴海东,杨隆浩",
  },
  {
    CourseName: "语文周一5-6",
    StartLesson: 5,
    EndLesson: 6,
    UserId: 1136,
    Week: 3,
    WeekDay: "周一",
    TeacherName: "吴海东,杨隆浩",
  },
  {
    CourseName: "地理周一3-4",
    StartLesson: 3,
    EndLesson: 4,
    Week: 3,
    WeekDay: "周一",
    TeacherName: "吴海东",
  },
  {
    CourseName: "基于Python的文本挖掘周三5-6",
    StartLesson: 5,
    EndLesson: 6,
    UserId: 1136,
    Week: 3,
    WeekDay: "周三",
    TeacherName: "林峰\t",
  },
  {
    CourseName: "大数据分析周五3-4",
    StartLesson: 3,
    EndLesson: 4,
    UserId: 1136,
    Week: 3,
    WeekDay: "周五",
    TeacherName: "陈海汉",
  },
  {
    CourseName: "历史周三3-4",
    StartLesson: 3,
    EndLesson: 4,
    UserId: 1136,
    Week: 3,
    WeekDay: "周三",
    TeacherName: "蓝以信",
  },
  {
    CourseName: "政治周一3-4",
    Id: 23988,
    StartLesson: 3,
    EndLesson: 4,
    UserId: 1136,
    Week: 3,
    WeekDay: "周一",
    TeacherName: "蓝以信",
  },
  {
    CourseName: "物理周一1-5",
    Id: 239811,
    StartLesson: 1,
    EndLesson: 5,
    UserId: 11344,
    Week: 3,
    WeekDay: "周一",
    TeacherName: "蓝以信1",
  },
  {
    CourseName: "物理周二1-4",
    Id: 239811,
    StartLesson: 1,
    EndLesson: 4,
    UserId: 11344,
    Week: 3,
    WeekDay: "周二",
    TeacherName: "蓝以信1",
  },
  {
    CourseName: "物理周二2-3",
    Id: 239811,
    StartLesson: 2,
    EndLesson: 3,
    UserId: 11344,
    Week: 3,
    WeekDay: "周二",
    TeacherName: "122",
  },
  {
    CourseName: "物理周三1-7",
    Id: 239811,
    StartLesson: 1,
    EndLesson: 7,
    UserId: 11344,
    Week: 3,
    WeekDay: "周三",
    TeacherName: "蓝以信1",
  },
  {
    CourseName: "历史周三1-11",
    Id: 239811,
    StartLesson: 1,
    EndLesson: 11,
    UserId: 11344,
    Week: 3,
    WeekDay: "周三",
    TeacherName: "蓝以信1",
  },
  {
    CourseName: "物理周四7-11",
    Id: 239811,
    StartLesson: 7,
    EndLesson: 11,
    UserId: 11344,
    Week: 3,
    WeekDay: "周四",
    TeacherName: "蓝以信1",
  },
  {
    CourseName: "化学周四4-5",
    Id: 239811,
    StartLesson: 4,
    EndLesson: 5,
    UserId: 11344,
    Week: 3,
    WeekDay: "周四",
    TeacherName: "蓝以信1",
  },
  {
    CourseName: "数学周四6-7",
    Id: 239811,
    StartLesson:6,
    EndLesson: 7,
    UserId: 11344,
    Week: 3,
    WeekDay: "周四",
    TeacherName: "蓝以信1",
  },
  {
    CourseName: "英语周四6-9",
    Id: 239811,
    StartLesson:6,
    EndLesson: 9,
    UserId: 11344,
    Week: 3,
    WeekDay: "周四",
    TeacherName: "蓝以信1",
  },
];
